name: 编译镜像并发布到dockerhub

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: 登录docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}


    - name: checkout 
      uses: actions/checkout@v4

    - name: 编译并发布
      run: |
        cd ./docker 
        export version=$(date +%s)
        docker build . --file Dockerfile --tag pikaaq/vnc:$version
        docker push pikaaq/vnc:$version
        docker tag pikaaq/vnc:$version pikaaq/vnc:latest
        docker push pikaaq/vnc:latest



    
